[project]
name = "cantemo-av-lta-plugin"
version = "0.0.0"
description = "Integrates Accurate Video with Cantemo using LTA"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "mypy>=1.17.1",
    "pre-commit>=4.3.0",
    "types-requests>=2.32.4.20250809",
]

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120
py_version = "311"
force_single_line = true

[tool.mypy]
python_version = "3.11"
platform = 'linux'
mypy_path = "av_lta/"
ignore_missing_imports = true
files = ["av_lta/"]
exclude = [
    "migrations"
]
